handyman_website/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name="accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout", 
         auth_views.LogoutView.as_view(template_name="accounts/logout"), 
         name="logout"),
]

handyman_website/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('handyman_website.apps.public.urls')),
    path("accounts/", include('handyman_website.apps.accounts.urls')),
]

handyman_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name



class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length = 200)

    def __str__(self):
        return self.name


# Create your models here.
class UserProfile(models.Model):
    #ForeignKey - owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    #Settings
    is_full_name_displayed = models.BooleanField(default=True)
    #Details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

handyman_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

handyman_website/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
    print(request.user)
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

handyman_website/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h1>
    About
</h1>
{% endblock %}

handyman_website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type"submit">Login</button>
</form>


{% endblock %}

handyman_website/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}Logged out{% endblock %}

{% block content %}
<form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">logout</button>
</form>

{% endblock %}

handyman_website/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<h1>
    {{ user.get_full_name }} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:"" }}
        </h2>
        <div>
            {{ profile.bio|default:"" }}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{website}}">{{ website }}</a>
            {% endwith %}
        </div>
        <br/>
        <div>
            Interests:
            {% for interest in profile.interests.all %}
                <span>
                    {{interest.name }}{% if not forloop.last %}, {% endif %}
                </span>
            {% endfor %}
        </div>
    {% endif %}    
{% endwith %}

{% endblock %}

handyman_website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}HandyMan{% endblock %}</title>
    </head>
<body>
    {% include 'navbar.html' %}
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

handyman_website/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>
    Contact
</h1>
{% endblock %}

handyman_website/templates/index.html
{% extends 'base.html' %}

{% block title %}Home👨🏼‍🔧{% endblock %}

{% block content %}
<h1>
    Home👨🏼‍🔧
</h1>
{% endblock %}

handyman_website/templates/navbar.html
<nav>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url }}">Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}">About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{{ contact_url }}">Contact</a>{% endif %}</span>
    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'profile' as profile_url %}
            <span>hi {% if request.path == profile_url %}{{ user.username }}{% else %}<a href="{{ profile_url }}">{{user.username}}</a></span>
            <span><a href="{% url 'accounts:logout' %}">Logout</a></span>
            {% endif %}
            {% else %}
            <span><a href="{% url 'accounts:login' %}">Login</a></span>
        {% endif %}
    </span>
</nav>